name: NotAbbott.com
favicon: null
layout_spectrum: 0.49977
typography_spectrum: 0.99352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#291026'
    - '#fefca5'
    - '#e58970'
    - '#f7baa0'
    - '#5570c8'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
