name: NotAbbott.com
favicon: null
layout_spectrum: 0.5443180005531758
typography_spectrum: 0.64795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#280f24'
    - '#f29b87'
    - '#fefca7'
    - '#56609c'
    - '#b7beec'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
